-- AlterTable
ALTER TABLE `Tag` MODIFY `tag1` VARCHAR(191) NULL,
    MODIFY `tag2` VARCHAR(191) NULL,
    MODIFY `tag3` VARCHAR(191) NULL,
    MODIFY `tag4` VARCHAR(191) NULL,
    MODIFY `tag5` VARCHAR(191) NULL;
